In [1]:
# import sys
# sys.setrecursionlimit(10000)
from time import time
import numpy as np
from Tree.tree_builder import tree_builder
from Tree.tree_values import TreeValues
from Tree.strategy_filling import strategy_filling
# from Tree.tree_visualizer import tree_visualizer
from Tree.tree_cfr import TreeCFR
from helper_classes import TreeParams, Node
from Game.card_to_string_conversion import card_to_string
from Game.card_tools import card_tools
from Settings.constants import constants
from Settings.arguments import arguments
from Settings.game_settings import game_settings
from Nn.value_nn import ValueNn
from Nn.next_round_value import NextRoundValue
from Nn.mock_nn_terminal import MockNnTerminal
from TerminalEquity.terminal_equity import TerminalEquity

In [2]:
PC = constants.players_count
CC = game_settings.card_count
P1 = constants.players.P1
P2 = constants.players.P2

# Tree Build

In [3]:
# params = TreeParams()
# params.limit_to_street = True
# first_node = Node()
# first_node.board = np.zeros([], dtype=int)
# first_node.street = 1
# first_node.current_player = constants.players.P1
# first_node.bets = np.array([arguments.ante, arguments.ante], dtype=int)
# params.root_node = first_node
# params.limit_to_street = True

# root = tree_builder.build_tree(params)
# strategy_filling.fill_uniform(root)

In [4]:
# tree_visualizer.draw_tree(root, size='30,10', show_vars=True)

In [5]:
# params = TreeParams()
# params.root_node = Node()
# params.root_node.board = card_to_string.string_to_board('Ks')
# params.root_node.street = 2
# params.root_node.current_player = constants.players.P2
# params.root_node.bets = np.array([300, 300])
# params.limit_to_street = False
# root = tree_builder.build_tree(params)
# tree_visualizer.draw_tree(root, size='20,10')

# Exploitability

In [6]:
# params = TreeParams()

# params.root_node = Node()
# params.root_node.board = card_to_string.string_to_board('')
# params.root_node.street = 1
# params.root_node.current_player = constants.players.P1
# params.root_node.bets = np.array([100, 100])

# tree = tree_builder.build_tree(params)

# tree_values = TreeValues()

# starting_ranges = np.zeros([PC,CC], dtype=arguments.dtype)
# starting_ranges[0] = card_tools.get_uniform_range(params.root_node.board)
# starting_ranges[1] = card_tools.get_uniform_range(params.root_node.board)

# tree_values.compute_values(tree, starting_ranges)

# print('Exploitability: ' + str(tree.exploitability) + ' [chips]' )

# CFR

In [7]:
# params = TreeParams()

# params.root_node = Node()
# params.root_node.board = card_to_string.string_to_board('')
# params.root_node.street = 1
# params.root_node.current_player = constants.players.P1
# params.root_node.bets = np.array([100, 100])

# tree = tree_builder.build_tree(params)

# starting_ranges = np.zeros([PC,CC], dtype=arguments.dtype)
# starting_ranges[0] = card_tools.get_uniform_range(params.root_node.board)
# starting_ranges[1] = card_tools.get_uniform_range(params.root_node.board)

# t0 = time()
# tree_cfr = TreeCFR()
# %lprun -f tree_cfr.cfrs_iter_dfs tree_cfr.run_cfr(tree, starting_ranges)
# print('Took time: {} for {} iters'.format(time()-t0, arguments.cfr_iters))

# tree_values = TreeValues()
# tree_values.compute_values(tree, starting_ranges)

# print('Exploitability: ' + str(tree.exploitability) + ' [chips]' )

# Card and Range Generator

In [8]:
# from DataGeneration.random_card_generator import card_generator
# card_generator.generate_cards(6)

In [9]:
# from DataGeneration.range_generator import RangeGenerator
# r = RangeGenerator()
# board = np.zeros([])
# r.set_board(board)
# BS,CC = 10,6
# ranges = np.zeros([BS,CC])
# r.generate_range(ranges)
# print(np.array2string(ranges, suppress_small=True, precision=2))
# print(np.array2string(np.sum(ranges, axis=1, keepdims=True), suppress_small=True, precision=2))

# Lookahead (test 1)

In [10]:
# params = TreeParams()
# params.root_node = Node()
# params.root_node.board = card_to_string.string_to_board('Ks')
# params.root_node.street = 2
# params.root_node.current_player = constants.players.P1
# params.root_node.bets = np.array([100, 100])
# params.limit_to_street = False
# tree = tree_builder.build_tree(params)

In [11]:
# from Tree.tree_strategy_filling import TreeStrategyFilling

# filling = TreeStrategyFilling()

# range1 = card_tools.get_uniform_range(params.root_node.board)
# range2 = card_tools.get_uniform_range(params.root_node.board)

# filling.fill_strategies(tree, P1, range1, range2)
# filling.fill_strategies(tree, P2, range1, range2)

In [12]:
# starting_ranges = np.zeros([PC,CC], dtype=arguments.dtype)
# starting_ranges[0] = card_tools.get_uniform_range(params.root_node.board)
# starting_ranges[1] = card_tools.get_uniform_range(params.root_node.board)

# tree_values = TreeValues()
# tree_values.compute_values(tree, starting_ranges)

# print('Exploitability: ' + str(tree.exploitability) + ' [chips]' )

# Next Round Value Bucketing test

In [16]:
# next_round_value = NextRoundValue(None)
# print(next_round_value._range_matrix)
# # test of card to bucket range translation
# range_ = np.arange(1,7).reshape([1,-1]).astype(float)
# next_round_range = np.zeros([1, next_round_value.bucket_count * next_round_value.board_count], dtype=arguments.dtype)
# next_round_value._card_range_to_bucket_range(range_, next_round_range)
# print(next_round_range)

# Next Round Value (mock test)

In [15]:
# # # test of get_value functionality
# mock_nn = MockNnTerminal()
# # mock_nn = ValueNn()
# next_round_value = NextRoundValue(mock_nn)

# # bets = np.array([100], dtype=float)
# bets = np.array([1200], dtype=float)

# next_round_value.start_computation(bets)

# ranges = np.full([1,2,CC], 1/4, dtype=arguments.dtype)
# values = np.zeros([1,2,CC], dtype=arguments.dtype)

# np.random.seed(0)
# ranges[0][0] = np.array([1,1,0,0,0,0])
# ranges[0][1] = np.array([1,1,1,1,1,1])

# next_round_value.get_value(ranges, values)

# print(values)

# ranges_2 = ranges.reshape([2,CC]).copy()
# values_2 = np.full_like(ranges_2, -1)

# terminal_equity = TerminalEquity()
# terminal_equity.set_board(np.zeros([]))
# terminal_equity.call_value(ranges_2, values_2)
# print('terminal_equity')
# print(values_2)

# # output:
# # [[[ 2.  2.  0.  0. -2. -2.]
# #   [ 0.  0. -1. -1. -1. -1.]]]
# # terminal_equity
# # [[ 0.  0. -1. -1. -1. -1.]
# #  [ 2.  2.  0.  0. -2. -2.]]

[[[ 2.  2.  0.  0. -2. -2.]
  [ 0.  0. -1. -1. -1. -1.]]]
terminal_equity
[[ 0.  0. -1. -1. -1. -1.]
 [ 2.  2.  0.  0. -2. -2.]]


In [ ]:
# # needs to comment out some asserts and use_memory = True

# board = card_to_string.string_to_board('Ks')

# values_3 = np.full_like(values, -1)
# next_round_value.get_value_on_board(board, values_3)

# print(values_3)

# # output:
# # [[[ 0.2  0.2  0.   0.8 -0.6 -0.6]
# #   [ 0.   0.   0.   1.  -1.  -1. ]]]